import numpy as np
import pandas as pd

# df = pd.DataFrame({
#     'EmployeeID': [1,2,3,4,5,6],
#     'EmployeeName': ['A','B','C','D','E','F'],
#     'Department': ['HR','IT','HR','IT','Finance','Finance'],
#     'Salary': [50000, 60000, 55000, 65000, 70000, 72000]
# })

# # Q1: Calculate the average salary of employees in each department.
# # print(df.groupby("Department")["Salary"].mean())


# df2 = pd.DataFrame({
#     'ProductName': ['Pen','Pencil','Pen','Notebook','Pencil','Notebook'],
#     'QuantitySold': [10, 15, 8, 20, 12, 18]
# })

# # Find the total quantity sold for each product.
# # print(df2.groupby("ProductName")["QuantitySold"].sum())

# df3 = pd.DataFrame({
#     'EmployeeID': [1,2,3,4,5,6],
#     'EmployeeName': ['A','B','C','D','E','F'],
#     'City': ['Delhi','Mumbai','Delhi','Pune','Mumbai','Delhi']
# })

# # Determine the number of employees working in each city.
# # print(df3.groupby("City")["EmployeeName"].count())

# df4 = pd.DataFrame({
#     'Category': ['Electronics','Clothing','Electronics','Clothing','Grocery','Grocery'],
#     'Revenue': [50000, 20000, 45000, 25000, 15000, 18000]
# })
# # Calculate the total revenue generated by each category.
# # print(df4.groupby("Category")["Revenue"].sum())



# # Q5. Reuse the df from Q1 (EmployeeID, EmployeeName, Department, Salary).
# # Find the maximum salary in each department.

# # print(df.groupby("Department")["Salary"].max())


# df6 = pd.DataFrame({
#     'StudentName': ['Aman','Priya','Rahul','Sneha','Karan','Riya'],
#     'Class': ['10A','10B','10A','10B','10A','10B'],
#     'Marks': [85, 90, 78, 88, 92, 81]
# })
# # Calculate the average marks obtained by students from each class.
# # print(df6.groupby("Class")["Marks"].mean())


# df7 = pd.DataFrame({
#     'CustomerID': [101, 102, 101, 103, 102, 101],
#     'PurchaseAmount': [500, 1200, 300, 800, 450, 700]
# })
# # Calculate the total amount spent by each customer.
# # print(df7.groupby("CustomerID")["PurchaseAmount"].sum())

# df8 = pd.DataFrame({
#     'Branch': ['North','South','North','East','South','East'],
#     'Profit': [25000, 18000, 22000, 30000, 20000, 28000]
# })
# # Find the average profit earned by each branch.
# # print(df8.groupby("Branch")["Profit"].mean())


# df9 = pd.DataFrame({
#     'Month': ['Jan','Feb','Jan','Mar','Feb','Mar'],
#     'Sales': [10000, 12000, 9000, 15000, 11000, 14000]
# })
# # Determine the total sales for each month
# # print(df9.groupby("Month")["Sales"].sum())


# # Q10. Reuse df from Q1 (EmployeeID, EmployeeName, Department, Salary).
# # Calculate the mean, maximum, minimum, and count of salaries department-wise using a single groupby() operation.
# # This is the first one where you need .agg() to get multiple stats at once. Give it a try.
# # print(df.groupby("Department")["Salary"].agg(["mean","max","min","count"]))



# ---------------------------------------------------------------------------------------
# Pivot table


# df = pd.DataFrame({
#     'Department': ['HR','HR','IT','IT','Finance','Finance'],
#     'Gender': ['M','F','M','F','M','F'],
#     'Salary': [50000, 52000, 60000, 62000, 70000, 71000]
# })
# df = pd.DataFrame(df)
# # Create a pivot table that shows the average salary of male and female employees in each department.
# result  =  pd.pivot_table(
#     df,
#     values="Salary",
#     index="Department",
#     columns="Gender",
#     aggfunc="mean",
# )
# print(result)

# dfp2 = pd.DataFrame({
#     'Product': ['Pen','Pencil','Notebook','Pen','Pencil','Notebook'],
#     'Sales': [500, 300, 700, 450, 350, 650]
# })
# # Create a pivot table showing total sales for each product.
# dfp2 = pd.DataFrame(dfp2)

# result = pd.pivot_table(
#     dfp2,
#     values="Sales",
#     index="Product",
#     aggfunc="sum"
# )
# print(result)


# dfp3 = pd.DataFrame({
#     'Region': ['North','South','North','South','North','South'],
#     'Year': [2023,2023,2024,2024,2025,2025],
#     'Revenue': [100000, 90000, 120000, 95000, 130000, 100000]
# })
# # Create a pivot table showing total revenue generated in each region across different years.
# dfp3 = pd.DataFrame(dfp3)

# print(pd.pivot_table(
#     dfp3,
#     values="Revenue",
#     index="Region",
#     aggfunc="sum",
#     columns="Year"
# ))

# dfp4 = pd.DataFrame({
#     'StudentName': ['Aman','Aman','Priya','Priya','Rahul','Rahul'],
#     'Subject': ['Math','Science','Math','Science','Math','Science'],
#     'Marks': [85, 90, 78, 88, 92, 81]
# })
# # Create a pivot table showing marks obtained by each student in different subjects.
# result = pd.pivot_table(
#     dfp4,
#     values="Marks",
#     index ="StudentName",
#     aggfunc="sum",
#     columns="Subject"
# )
# print(result)


# dfp5 = pd.DataFrame({
#     'Branch': ['North','North','South','South','East','East'],
#     'Quarter': ['Q1','Q2','Q1','Q2','Q1','Q2'],
#     'Profit': [20000, 22000, 18000, 19000, 25000, 27000]
# })
# # Create a pivot table showing branch-wise profit for every quarter.

# print(pd.pivot_table(
#     dfp5,
#     values="Profit",
#     index="Branch",
#     columns="Quarter",
#     aggfunc="sum"
# ))

# dfp6 = pd.DataFrame({
#     'EmployeeID': [1,2,3,4,5,6],
#     'Department': ['HR','IT','HR','Finance','IT','Finance']
# })
# # Create a pivot table to count the number of employees in each department

# print(pd.pivot_table(
#     dfp6,
#     values="EmployeeID",
#     index="Department",
#     aggfunc="count"
# ))

# dfp7 = pd.DataFrame({
#     'Product': ['Pen','Pen','Pencil','Pencil','Notebook','Notebook'],
#     'Region': ['North','South','North','South','North','South'],
#     'Sales': [500, 450, 300, 350, 700, 650]
# })
# # Create a pivot table showing region-wise sales of each product.

# dfp8 = pd.DataFrame({
#     'StudentName': ['Aman','Aman','Priya','Priya','Rahul','Rahul'],
#     'Month': ['Jan','Feb','Jan','Feb','Jan','Feb'],
#     'Attendance': [85, 90, 95, 92, 80, 88]
# })
# # Create a pivot table showing monthly attendance of each student.
# print(pd.pivot_table(
#     dfp8,
#     values="Attendance",
#     index="StudentName",
#     columns="Month",
#     aggfunc="sum"
# ))

# dfp9 = pd.DataFrame({
#     'Category': ['Electronics','Clothing','Electronics','Grocery','Clothing','Grocery'],
#     'OrderID': [101, 102, 103, 104, 105, 106]
# })
# # Create a pivot table showing the total number of orders in each category.
# print(pd.pivot_table(
#     dfp9,
#     values="OrderID",
#     index="Category",
#     aggfunc="count"
# ))

# df = pd.DataFrame({
#     'EmployeeID': [1,2,3,4,5,6],
#     'EmployeeName': ['A','B','C','D','E','F'],
#     'Department': ['HR','IT','HR','IT','Finance','Finance'],
#     'Salary': [50000, 60000, 55000, 65000, 70000, 72000]
# })
# # Create a pivot table that displays the average, maximum, and minimum salary for each department.
# print(pd.pivot_table(
#     df,
#     values="Salary",
#     index="Department",
#     aggfunc=["mean","max","min"]
# ))


